all.Carsm<-function(){
     cat("\n")
     note_for_CBZsm_input()
     cat("\n")
     note_for_close_window()
     CBZSMMpar<-data.frame(parameter=c("TBW (kg)","PB","VPA","PHT","E","D (mg)","tau (hr)"),value=c(75,0,1,0,1,400,12))
     CBZSMMpar<-edit(CBZSMMpar)
     show(CBZSMMpar);cat("\n\n")
     ### CBZSMMpar<-ycheck(CBZSMMpar)
     cat("\n")
     note_for_CBZsm_conc_input()
     cat("\n")
     note_for_close_window()
     CBZSMpar<-data.frame(ts=c(6,10),conc=c(14.5,12.7))
     CBZSMpar<-edit(CBZSMpar)
     ### CBZSMpar<-mscheck(CBZSMpar)
     show(CBZSMpar);cat("\n\n")
     cat("\n")
     Car.sm(length(CBZSMpar$ts),CBZSMpar$conc,CBZSMpar$ts,CBZSMMpar[7,2],CBZSMMpar[6,2],CBZSMMpar[1,2],CBZSMMpar[2,2],
           CBZSMMpar[3,2],CBZSMMpar[4,2],CBZSMMpar[5,2])
     note_for_convergence_plots()
     ### convergence_plots_sep()
     note_for_CBZsm_output()
     ### show(samplesStats("*"))
     ### show obs. and calc. conc. here  -YJ
     cat("\n\n")
     for(i in 1:length(CBZSMpar$ts)){
         Cx<-pocpr(1.2,CBZSMMpar[6,2],CBZSMMpar[7,2],CBZSMpar$ts[i])
         coutput<-data.frame(conc=c("obs. conc.","calc. conc."), values=c(CBZSMpar$conc[i],Cx))
         cat("--- CBZ plasma conc. (mg/L) at Time =",CBZSMpar$ts[i],"---\n")
         show(coutput);cat("\n")
     }
     cat("\n")
     C<-pocpr(1.2,CBZSMMpar[6,2],CBZSMMpar[7,2],CBZSMMpar[7,2])  ### here 1.2 is 'ka', as default value.  -YJ
     ### sim<-matrix(C[1 ,1])
     coutput<-data.frame(C)
     colnames(coutput)<-list("Ctss_pr (mg/L)")
     show(coutput)     
     cat("\n")
     Car.more()  
}