all.Tacsm<-function(){
     cat("\n")
     note_for_Tacsm_input()
     cat("\n")
     note_for_close_window()
     ### TacSMMpar<-data.frame(parameter=c("Hem","Alb","Dil","Flu","D (mg)","tau (hr)"),value=c(0))
     TacSMMpar<-data.frame(parameter=c("Hem","Alb","Dil","Flu","D (mg)","tau (hr)"),value=c(1,0,1,0,10,12))
     TacSMMpar<-edit(TacSMMpar)
     cat("\n")
     cat("\n Input data are as follows:\n")
     cat(" --------------------------\n")
     show(TacSMMpar);cat("\n\n")
##     TacSMMpar<-ycheck(TacSMMpar)
     cat("\n")
     note_for_Tacsm_conc_input()
     cat("\n")
     note_for_close_window()
     TacSMpar<-data.frame(ts=c(6,10),conc=c(23.1,17.5))
     TacSMpar<-edit(TacSMpar)
     ### TacSMpar<-mscheck(TacSMpar)
     cat("\n")
     cat("\n Input conc. are as follows:\n")
     cat(" --------------------------\n")
     show(TacSMpar);cat("\n\n")
     cat("\n")
     Tac.sm(length(TacSMpar$ts),TacSMpar$conc,TacSMpar$ts,TacSMMpar[6,2],TacSMMpar[5,2],TacSMMpar[1,2],TacSMMpar[2,2],TacSMMpar[3,2],TacSMMpar[4,2])
     note_for_convergence_plots()
     ### convergence_plots_sep()
     note_for_Tacsm_output()
     ### show(samplesStats("*"))
     ### show obs. and calc. conc. here  -YJ
     cat("\n\n")
     for(i in 1:length(TacSMpar$ts)){
         Cx<-Taccpr(4.5,TacSMMpar[5,2],TacSMMpar[6,2],TacSMpar$ts[i])  ### here 4.5 is 'ka'& 'vd' = 314 L (see TacSSmode.txt);
         coutput<-data.frame(conc=c("obs. conc.","calc. conc."), values=c(TacSMpar$conc[i],Cx))
         cat("--- Tacrolimus blood conc. (mcg/L) at Time =",TacSMpar$ts[i],"---\n")
         show(coutput);cat("\n")
     }
     cat("\n") 
     C<-Taccpr(4.5,TacSMMpar[5,2],TacSMMpar[6,2],TacSMMpar[6,2])  ### here 4.5 is 'ka'& 'vd' = 314 L (see TacSSmode.txt);
     ### sim<-matrix(C[1 ,1])
     coutput<-data.frame(C)
     colnames(coutput)<-list("Ctss_pr (mcg/mL)")
     show(coutput)    
     cat("\n")      
     Tac.more()
}