all.Imams<-function(){
     cat("\n")
     note_for_Imass_input()
     cat("\n")
     cat("****************************************************************\n")
     cat("      ATTENTION :                                               \n")
     cat("      Sampling Time (ts) must be greater than 1.5 hr.           \n")
     cat("****************************************************************\n")
     cat("\n\n")
     cat("          Pressing Enter to continue..                          \n")
     readline()
     cat("\n")
     note_for_close_window()
     ImaMSpar<-data.frame(subject=c(1,2),BW=c(0),OCC=c(0),Hb=c(0),WBC=c(0),n=c(0),D=c(0),tau=c(0),ts=c(0),c=c(0))
     ImaMSpar<-edit(ImaMSpar)
##     ImaMSpar<-ymscheck(ImaMSpar)
     cat("\n")
     Ima.ms(length(ImaMSpar$subject),ImaMSpar$c,ImaMSpar$ts,ImaMSpar$tau,ImaMSpar$n,ImaMSpar$D,ImaMSpar$OCC,ImaMSpar$BW,ImaMSpar$Hb,ImaMSpar$WBC)
     note_for_convergence_plots()
     note_for_plot()
     convergence_plots_con()
     note_for_Imass_output()    
     show(samplesStats("*"))
     cat("\n") 
     C<-Imacpr(ImaMSpar$n,ImaMSpar$D,ImaMSpar$tau,ImaMSpar$ts)
     sim<-matrix(C[ ,1])
     coutput<-data.frame(sim)
     colnames(coutput)<-list("Cm_pr (mg/L)")
     output1<-coutput
     show(coutput)
     C<-Imasscpr(ImaMSpar$D,ImaMSpar$tau)
     sim<-matrix(C[ ,1])
     coutput<-data.frame(sim)
     colnames(coutput)<-list("Ctss_pr (mg/L)")
     output3<-coutput
     show(coutput)    
     cat("\n")
     cal.again()
}