all.Indss<-function(){
     cat("\n")
     note_for_Indss_input()
     cat("\n")
     note_for_close_window()
     IndSSpar<-data.frame(parameter=c("Gender","bw (kg)","Rit","D (mg)","tau (hr)","ts (hr)","c (mg/L)"),
                          value=c(0,72,1,800,8,6,2.1))
     IndSSpar<-edit(IndSSpar)
     cat("\n Input data are as follows:\n")
     cat(" --------------------------\n")
     show(IndSSpar);cat("\n\n")
##     IndSSpar<-ycheck(IndSSpar)
     Ind.ss(IndSSpar[7,2],IndSSpar[5,2],IndSSpar[6,2],IndSSpar[4,2],IndSSpar[2,2],IndSSpar[3,2],IndSSpar[1,2])
     note_for_convergence_plots()
     ### convergence_plots_sep()
     note_for_Indss_output()
     ### show(samplesStats("*"))
     cat("\n") 
     C1<-Indcpr(IndSSpar[4,2],IndSSpar[5,2],IndSSpar[6,2])
     C2<-Indcpr(IndSSpar[4,2],IndSSpar[5,2],IndSSpar[5,2])  ### original code was wrong!  -YJ
     coutput<-data.frame(conc=c("Cmss_obs","Cmss_pr","Ctss_pr"),value=c(IndSSpar[7,2],C1,C2))
     show(coutput)    
     cat("\n")  
     Ind.more()
}