all.Indsm<-function(){
     cat("\n")
     note_for_Indsm_input()
     cat("\n")
     note_for_close_window()
     IndSMMpar<-data.frame(parameter=c("Gender","bw (kg)","Rit","D (mg)","tau (hr)"),value=c(0,72,1,800,8))
     IndSMMpar<-edit(IndSMMpar)
     cat("\n Input data are as follows:\n")
     cat(" --------------------------\n")
     show(IndSMMpar);cat("\n\n")
##     IndSMMpar<-zcheck(IndSMMpar)
     cat("\n")
     note_for_Indsm_conc_input()
     note_for_close_window()
     IndSMpar<-data.frame(ts=c(6,8),conc=c(3.1,1.2))
     IndSMpar<-edit(IndSMpar)
     ### IndSMpar<-mscheck(IndSMpar)
     show(IndSMpar);cat("\n\n")
     cat("\n")
     Ind.sm(length(IndSMpar$ts),IndSMpar$conc,IndSMpar$ts,IndSMMpar[5,2],IndSMMpar[4,2],IndSMMpar[2,2],IndSMMpar[3,2],IndSMMpar[1,2])
     note_for_convergence_plots()
     ### convergence_plots_sep()
     ### show obs. and calc. conc. here  -YJ
     cat("\n\n")
     for(i in 1:length(IndSMpar$ts)){
         Cx<-Indcpr(IndSMMpar[4,2],IndSMMpar[5,2],IndSMpar$ts[i]) 
         coutput<-data.frame(conc=c("obs. conc.","calc. conc."), values=c(IndSMpar$conc[i],Cx))
         cat("--- Indinavir plasma conc. (mg/L) at Time =",IndSMpar$ts[i],"---\n")
         show(coutput);cat("\n")
     }
     note_for_Indsm_output()
     ### show(samplesStats("*"))
     cat("\n") 
     C<-Indcpr(IndSMMpar[4,2],IndSMMpar[5,2],IndSMMpar[5,2])
     ### sim<-matrix(C[1 ,1])
     coutput<-data.frame(C)
     colnames(coutput)<-list("Ctss_pr (mg/L)")
     show(coutput)    
     cat("\n") 
     Ind.more()
}