all.Valss<-function(){
     cat("\n")
     note_for_Valss_input()
     cat("\n")
     note_for_close_window()
     ValSSpar<-data.frame(parameter=c("age (yr)","INDI","CBZ","ka","D (mg)","tau (hr)","ts (hr)","c (mg/L)"),value=c(0))
     ValSSpar<-edit(ValSSpar)
##     ValSSpar<-ycheck(ValSSpar)
     cat("\n")
     Val.ss(ValSSpar[8,2],ValSSpar[6,2],ValSSpar[7,2],ValSSpar[5,2],ValSSpar[1,2],ValSSpar[3,2],ValSSpar[2,2],ValSSpar[4,2])
     note_for_convergence_plots()
     convergence_plots_sep()
     note_for_Valss_output()
     show(samplesStats("*"))
     cat("\n") 
     C<-Valcpr(ValSSpar[4,2],ValSSpar[5,2],ValSSpar[6,2],ValSSpar[7,2])
     sim<-matrix(C[1 ,1])
     coutput<-data.frame(sim)
     colnames(coutput)<-list("Cmss_pr (mg/L)")
     output1<-coutput
     show(coutput)
     C<-Valcpr(ValSSpar[4,2],ValSSpar[5,2],ValSSpar[6,2],ValSSpar[6,2])
     sim<-matrix(C[1 ,1])
     coutput<-data.frame(sim)
     colnames(coutput)<-list("Ctss_pr (mg/L)")
     output2<-coutput
     show(coutput)    
     cat("\n")   
     Val.more(ValSSpar[4,2])
}