all.Ritsm<-function(){
     cat("\n")
     note_for_Ritsm_input()
     cat("\n")
     note_for_close_window()
     RitSMMpar<-data.frame(parameter=c("LPV","D (mg)","tau (hr)"),
                           value=c(1,200,24))
     RitSMMpar<-edit(RitSMMpar)
     cat("\n Input data are as follows:\n")
     cat(" --------------------------\n")
     show(RitSMMpar);cat("\n\n")
##     RitSMMpar<-wcheck(RitSMMpar)
     note_for_Ritsm_conc_input()
     note_for_close_window()
     RitSMpar<-data.frame(ts=c(12,22),conc=c(78.3,54.3))
     RitSMpar<-edit(RitSMpar)
     ### RitSMpar<-mscheck(RitSMpar)
     cat("\n Input conc. data are as follows:\n")
     cat(" --------------------------------\n")
     show(RitSMpar);cat("\n\n")
     Rit.sm(length(RitSMpar$ts),RitSMpar$conc,RitSMpar$ts,RitSMMpar[3,2],RitSMMpar[2,2],RitSMMpar[1,2])
     note_for_convergence_plots()
     ### convergence_plots_sep()
     ### show obs. and calc. conc. here  -YJ
     cat("\n\n")
     for(i in 1:length(RitSMpar$ts)){
         Cx<-Ritcpr(RitSMMpar[2,2],RitSMMpar[3,2],RitSMpar$ts[i]) 
         coutput<-data.frame(conc=c("obs. conc.","calc. conc."), values=c(RitSMpar$conc[i],Cx))
         cat("--- Ritonavir plasma conc. (mcg/L) at Time =",RitSMpar$ts[i],"---\n")
         show(coutput);cat("\n")
     }
     note_for_Ritsm_output()
     ### show(samplesStats("*"))
     C<-Ritcpr(RitSMMpar[2,2],RitSMMpar[3,2],RitSMMpar[3,2])
     ### sim<-matrix(C[1 ,1])
     coutput<-data.frame(C)
     colnames(coutput)<-list("Ctss_pr (mcg/L)")
     show(coutput)    
     cat("\n") 
     Rit.more()
}