all.Warms<-function(){
     cat("\n")
     note_for_War_input()
     cat("\n")
     note_for_close_window()
     WarMSpar<-data.frame(subject=c(1,2),D=c(0),tau=c(0),INR=c(0))
     WarMSpar<-edit(WarMSpar)
     WarMSpar<-wmscheck(WarMSpar)
     cat("\n")
     War.ms(length(WarMSpar$subject),WarMSpar$D,WarMSpar$tau,WarMSpar$INR)
     note_for_convergence_plots()
     note_for_plot()
     convergence_plots_con()
     note_for_War_output()
     show(samplesStats("*"))
     cat("\n")
     C<-Warcpr(WarMSpar$D,WarMSpar$tau)  
     sim<-matrix(C[ ,1])
     coutput<-data.frame(sim)
     colnames(coutput)<-list("INR (mg/L)")
     show(coutput)  
     cat("\n") 
     cal.again()
}