Ami.sm<-function(a,b,c,d,e,f,g,h,i,j,k){
library(BRugs)
oldwd<-getwd()
setwd(system.file("PK",package="tdm"))
modelCheck("AmiSMmodel.txt")
bugsData(
list(T=a,
c=c(b),
ts=c(c),
tau=d,
tin=e,
D=f,
bw=g,
Ht=h,
Scr=i,
Gender=j,
age=k
)
, fileName=file.path(getwd(),"Amidata.txt"),digits=5)
modelData("Amidata.txt")
modelCompile(numChains=1)
modelGenInits()
modelUpdate(4000)
samplesSet(c("v_F","cl_F"))
modelUpdate(10000)
}
